import type { Metadata } from "next";
import { Montserrat,Roboto  } from 'next/font/google';
import "./globals.css";


// configure the montserrat font
const montserrat = Montserrat({
  subsets: ['latin'], // Choose subsets according to your needs
  weights: [400, 700], // Include font weights you plan to use
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>{children}</body>
    </html>
  );
}
