import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
  // Favicon
  icons: {
    icon: '/favicon.ico', // Path to your favicon.ico file
  },

  // Open Graph meta tags (for social media sharing)
  openGraph: {
    title: "Create Next App",  // Title for social media
    description: "Generated by create next app", // Description for social media
    url: "https://yourwebsite.com", // URL of your website
    siteName: "Create Next App", // Site name
    images: [
      {
        url: "/og-image.jpg", // Image for Open Graph (make sure to provide a valid image path)
        width: 1200,
        height: 630,
        alt: "Create Next App", // Alt text for the image
      },
    ],
  },

  // Twitter meta tags
  twitter: {
    card: "summary_large_image", // Type of card (can be 'summary', 'summary_large_image', 'app', etc.)
    site: "@YourTwitterHandle",  // Twitter handle for the site
    creator: "@YourTwitterHandle", // Twitter handle of the content creator (optional)
    title: "Create Next App", // Title for Twitter sharing
    description: "Generated by create next app", // Description for Twitter
    images: [
      "/og-image.jpg", // Image for Twitter (make sure to provide a valid image path)
    ],
  },
};
