import type { Metadata } from "next";

// STYLING
import "../../public/css/globals.css";



// META
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bodyWrapper"
      >
        {children}
      </body>
    </html>
  );
}
